name: Rust

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Scrape pronouns and prepositions
      run: cargo run --release
    - name: Download trunk
      run: wget -qO- https://github.com/trunk-rs/trunk/releases/download/0.21.13/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
    - name: Build website
      run: trunk build
    - name: Upload website artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: dist/
    - name: Deploy to GH Pages
      uses: actions/deploy-pages@v4.0.5
